FROM ${docker.registry.host}/${docker.base.image}
LABEL From="${docker.registry.host}/${docker.base.image}"
LABEL MAINTAINER="ATLAS DevOps"

# Uncomment the ENV and add Environment Variables here as needed.  Use  the format KEY=VALUE \ new line repeat new KEY=VALUE as often as needed
#ENV

# Uncomment the EXPOSE and add Ports that SHOULD BE EXPOSED here as needed.  Do NOT list ports that are internal to the running container
#EXPOSE

# Uncomment the CMD for SpringBoot based images that inherit the fabric8 run-java process, uncomment below.  Otherwise, change as appropriate
#CMD ./run-java.sh

# Uncomment the RUN and add any new image configuration requirements here. Use the \ newline format for more than 1.
# If using a package manager (yum/apt) to install new packages, ALWAYS USE A SPECIFIC VERSION NUMBER DEFINED IN YOUR PARENT POM
#RUN

# Uncomment the COPY and add any required options.  Use COPY in normal course of setup.  ADD when you want a tar/zip/bzip/gzip file to expand
#COPY


